# This file handles the installation and customization of Flower

- name: install flower to venv created by multiscanner
  pip:
    name: flower
    virtualenv: "{{ multiscanner_venv }}"
    virtualenv_python: "{{ python_install_prefix }}/bin/python"
    virtualenv_site_packages: yes
  become: yes
  become_user: "{{ ms_user }}"

# Service setup
- name: copy flower systemd config
  template: src=flower.service.j2 dest=/etc/systemd/system/flower.service mode=755 owner=multiscanner group=root
  become: yes
  become_user: root
  notify:
  - restart flower
