---

- name: delete gluster client tarball directory
  file:
    path: "{{ remote_resource_prefix }}/gluster_client.tgz"
    state: absent

- name: delete gluster client RPM directory
  file:
    path: "{{ remote_resource_prefix }}/gluster_client/"
    state: absent

- name: copy gluster client RPMs
  copy:
    src: "../../{{local_resource_prefix}}/gluster_client.tgz"
    dest: "{{remote_resource_prefix}}"

- name: unzip gluster client RPMs
  unarchive:
    src: "{{ remote_resource_prefix }}/gluster_client.tgz"
    dest: "{{ remote_resource_prefix }}"
    remote_src: yes
    creates: "{{ remote_resource_prefix }}/gluster_client"

- name: install gluster client
  yum:
    name: "{{remote_resource_prefix}}/gluster_client/{{ item}}"
    state: present
  with_items:
    - glusterfs-{{ gluster_version }}.rpm
    - glusterfs-api-{{ gluster_version }}.rpm
    - glusterfs-client-xlators-{{ gluster_version }}.rpm
    - glusterfs-fuse-{{ gluster_version }}.rpm
    - glusterfs-libs-{{ gluster_version }}.rpm
  become: yes
  become_user: root


# If you're not in an airgapped environment, comment out the two blocks above, and uncomment the two blocks below:
#- name: install gluster prereqs
#  yum: name=centos-release-gluster{{ dfs_gluster_centos_sig_version }}  state=present
#  become: yes
#  become_user: root
#
#- name: install glusterfs client
#  yum: name=glusterfs-client  state=present
#  become: yes
#  become_user: root

