---
# Service setup
- name: copy multiscanner systemd config
  template: src=mscan-rest-celery-beat.service.j2 dest=/etc/systemd/system/mscan-rest-celery-beat.service mode=755 owner=multiscanner group=root
  register: restart_ms_celery_beat_svc
  become: yes
  become_user: root

- name: enable celery beat to start on boot (RHEL/CentOS 7)
  systemd:
    state: started
    enabled: yes
    name: mscan-rest-celery-beat
  become: yes
  become_user: root

# We don't want this to be called before we set up the systemd file.
# However, we don't want the systemd setup to happen until the config files
# have been copied, or MS won't start. Hence this awkward placement...
- name: restart ms-rest-celery-beat if any configs changed
  systemd: state=restarted name=mscan-worker
  when: restart_ms_celery_beat_svc | changed
  become: yes
  become_user: root
