---

- name: delete gluster server tarball
  file:
    path: "{{ remote_resource_prefix }}/gluster_server.tgz"
    state: absent

- name: delete gluster server RPM directory
  file:
    path: "{{ remote_resource_prefix }}/gluster_server/"
    state: absent

- name: copy gluster server RPMs
  copy:
    src: "../../{{local_resource_prefix}}/gluster_server.tgz"
    dest: "{{remote_resource_prefix}}"

- name: unzip gluster server RPMs
  unarchive:
    src: "{{ remote_resource_prefix }}/gluster_server.tgz"
    dest: "{{ remote_resource_prefix }}"
    remote_src: yes
    creates: "{{ remote_resource_prefix }}/gluster_server"

- name: install gluster server
  yum:
    name: "{{remote_resource_prefix}}/gluster_server/{{ item}}"
    state: present
  with_items:
    - glusterfs-{{ gluster_version }}.rpm
    - glusterfs-api-{{ gluster_version }}.rpm
    - glusterfs-cli-{{ gluster_version }}.rpm
    - glusterfs-client-xlators-{{ gluster_version }}.rpm
    - glusterfs-fuse-{{ gluster_version }}.rpm
    - glusterfs-libs-{{ gluster_version }}.rpm
    - glusterfs-server-{{ gluster_version }}.rpm
  become: yes
  become_user: root



# If you're not in an airgapped environment, comment out the two blocks above, and uncomment the two blocks below:
#- name: install gluster prereqs
#  yum: name=centos-release-gluster{{ dfs_gluster_centos_sig_version }}  state=present
#  become: yes
#  become_user: root

#- name: install gluster
#  yum: name=glusterfs-server  state=present
#  become: yes
#  become_user: root

