---

- name: restart Kibana
  systemd: state=restarted name=kibana
  become: yes
  become_user: root

- name: restart Metricbeat
  systemd: state=restarted name=metricbeat
  become: yes
  become_user: root
