---

# create the MultiScanner service account user on all hosts
- name: add MultiScanner user
  action: user name={{ ms_user }} password={{ ms_password }} shell=/bin/bash home=/home/{{ ms_user}}
  become: yes
  become_user: root

- name: install firewalld
  yum:
    name: firewalld
    state: latest
  become: true

- name: enable firewalld on boot
  systemd:
    state: started
    enabled: yes
    name: firewalld
  become: true

- include: setup_metricbeat.yml
  tags: [ 'metricbeat' ]
