---

- name: DEBUG-is web ssl enabled
  debug: var=servers_use_ssl

- include: install_certs.yml
  when: servers_use_ssl|bool == True

- include: configure_mscan_web.yml
- include: setup_firewall_rules.yml